// GENERATED by tools/build-templates.mjs -- do not edit.
//
// Source templates: src/templates/main/*.html
// Regenerate:       node tools/build-templates.mjs
// Verified by:      test/templates.test.js, which fails if this drifts.
//
// Committed on purpose: Render serves this repository as-is, so a build
// that is not committed would mean the deployed site is not the repo.

// --- EntropyPanel ----------------------------------------------------
import { normalizeStyle as _normalizeStyle, createElementVNode as _createElementVNode, normalizeClass as _normalizeClass, toDisplayString as _toDisplayString, openBlock as _openBlock, createElementBlock as _createElementBlock, createCommentVNode as _createCommentVNode, createTextVNode as _createTextVNode, renderList as _renderList, Fragment as _Fragment } from '../vendor/vue.esm-browser.prod.js'

const _hoisted_1 = { class: "entropy-summary" }
const _hoisted_2 = { class: "entropy-total" }
const _hoisted_3 = ["title"]
const _hoisted_4 = ["title"]
const _hoisted_5 = /*#__PURE__*/_createElementVNode("span", {
  class: "entropy-how",
  "aria-hidden": "true"
}, "how?", -1)
const _hoisted_6 = {
  key: 1,
  class: "entropy-range",
  title: "Average time to guess, assuming the attacker knows your settings. Open the breakdown for all four scenarios."
}
const _hoisted_7 = { class: "entropy-parts" }
const _hoisted_8 = { class: "ep-bits" }
const _hoisted_9 = { class: "ep-label" }
const _hoisted_10 = {
  key: 0,
  class: "ep-note"
}
const _hoisted_11 = { class: "entropy-extras" }
const _hoisted_12 = {
  key: 0,
  class: "entropy-extra-line"
}
const _hoisted_13 = {
  key: 1,
  class: "entropy-extra-line"
}
const _hoisted_14 = { class: "entropy-crack" }
const _hoisted_15 = /*#__PURE__*/_createElementVNode("div", { class: "entropy-crack-title" }, "average time to guess, if attacked knowing your settings:", -1)
const _hoisted_16 = ["title"]
const _hoisted_17 = { class: "crack-label" }
const _hoisted_18 = { class: "crack-rate" }
const _hoisted_19 = { class: "crack-time" }

export function renderEntropyPanel(_ctx, _cache) {
  return (_ctx.entropy)
    ? (_openBlock(), _createElementBlock("details", {
        key: 0,
        class: _normalizeClass(["entropy-panel", { 'entropy-low': _ctx.entropy.total < _ctx.floor }])
      }, [
        _createElementVNode("summary", _hoisted_1, [
          _createElementVNode("span", {
            class: _normalizeClass(["entropy-meter", 'meter-' + _ctx.tier.id]),
            "aria-hidden": "true"
          }, [
            _createElementVNode("span", {
              class: "entropy-meter-fill",
              style: _normalizeStyle({ width: _ctx.pct + '%' })
            }, null, 4)
          ], 2),
          _createElementVNode("span", _hoisted_2, _toDisplayString(_ctx.entropy.total.toFixed(1)) + " bits", 1),
          _createElementVNode("span", {
            class: _normalizeClass(["entropy-tier", 'meter-' + _ctx.tier.id]),
            title: _ctx.tier.id === 'weak' ? ('Below ' + _ctx.floor + ' bits. Add a word, a character type, or length.') : ('The bar fills at 100 bits; ' + _ctx.floor + ' is the weak line, 60 good, 80 strong.')
          }, _toDisplayString(_ctx.tier.label), 11, _hoisted_3),
          (_ctx.delta !== null && _ctx.showDelta)
            ? (_openBlock(), _createElementBlock("span", {
                key: 0,
                class: _normalizeClass(["entropy-delta", _ctx.delta > 0 ? 'is-up' : 'is-down']),
                title: 'This password is ' + Math.abs(_ctx.delta).toFixed(1) + ' bits ' + (_ctx.delta > 0 ? 'stronger' : 'weaker') + ' than the previous one'
              }, _toDisplayString(_ctx.delta > 0 ? '▲' : '▼') + " " + _toDisplayString(Math.abs(_ctx.delta).toFixed(1)) + " vs last", 11, _hoisted_4))
            : _createCommentVNode("", true),
          _hoisted_5,
          (_ctx.range)
            ? (_openBlock(), _createElementBlock("span", _hoisted_6, [
                _createTextVNode("to guess: leaked database "),
                _createElementVNode("strong", null, _toDisplayString(_ctx.range.fast), 1),
                _createTextVNode(" · login with lockout "),
                _createElementVNode("strong", null, _toDisplayString(_ctx.range.lockout), 1)
              ]))
            : _createCommentVNode("", true)
        ]),
        _createElementVNode("ul", _hoisted_7, [
          (_openBlock(true), _createElementBlock(_Fragment, null, _renderList(_ctx.entropy.parts, (p) => {
            return (_openBlock(), _createElementBlock("li", {
              key: p.label,
              class: _normalizeClass({ 'ep-zero': p.bits === 0 })
            }, [
              _createElementVNode("span", _hoisted_8, _toDisplayString(p.bits === 0 ? '0' : '+' + p.bits.toFixed(1)), 1),
              _createElementVNode("span", _hoisted_9, _toDisplayString(p.label), 1),
              (p.note)
                ? (_openBlock(), _createElementBlock("span", _hoisted_10, _toDisplayString(p.note), 1))
                : _createCommentVNode("", true)
            ], 2))
          }), 128))
        ]),
        _createElementVNode("div", _hoisted_11, [
          (_ctx.perChar !== null)
            ? (_openBlock(), _createElementBlock("div", _hoisted_12, [
                _createTextVNode(_toDisplayString(_ctx.perChar.toFixed(2)) + " bits per character across " + _toDisplayString(_ctx.len) + " characters", 1),
                (_ctx.charsRef !== null)
                  ? (_openBlock(), _createElementBlock(_Fragment, { key: 0 }, [
                      _createTextVNode(" — random characters at this length could carry " + _toDisplayString(_ctx.charsRef.toFixed(0)) + " bits; the gap is what structure and memorability cost", 1)
                    ], 64))
                  : _createCommentVNode("", true)
              ]))
            : _createCommentVNode("", true),
          (_ctx.listRef !== null)
            ? (_openBlock(), _createElementBlock("div", _hoisted_13, " the same " + _toDisplayString(_ctx.words) + " words drawn from the flat Words list would carry " + _toDisplayString(_ctx.listRef.toFixed(1)) + " bits ", 1))
            : _createCommentVNode("", true),
          _createElementVNode("div", _hoisted_14, [
            _hoisted_15,
            (_openBlock(true), _createElementBlock(_Fragment, null, _renderList(_ctx.crackRows, (s) => {
              return (_openBlock(), _createElementBlock("div", {
                key: s.id,
                class: "entropy-crack-row",
                title: s.note
              }, [
                _createElementVNode("span", _hoisted_17, [
                  _createTextVNode(_toDisplayString(s.label), 1),
                  _createElementVNode("span", _hoisted_18, _toDisplayString(s.rateLabel), 1)
                ]),
                _createElementVNode("span", _hoisted_19, _toDisplayString(s.time), 1)
              ], 8, _hoisted_16))
            }), 128))
          ])
        ])
      ], 2))
    : _createCommentVNode("", true)
}

